//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABB.AC800PEC.DbConfigTool.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABB.AC800PEC.DbConfigTool.Shared.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About XPense.
        /// </summary>
        public static string ABOUT_WINDOW_HEADER {
            get {
                return ResourceManager.GetString("ABOUT_WINDOW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Accent.
        /// </summary>
        public static string ACCENT_SELECT_LABEL_TEXT {
            get {
                return ResourceManager.GetString("ACCENT_SELECT_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount range.
        /// </summary>
        public static string AMOUNT_RANGE_LABEL_TEXT {
            get {
                return ResourceManager.GetString("AMOUNT_RANGE_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the appearance changes?.
        /// </summary>
        public static string APPEAR_CHANGE_PROMPT {
            get {
                return ResourceManager.GetString("APPEAR_CHANGE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string APPEARANCE_SECTION {
            get {
                return ResourceManager.GetString("APPEARANCE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied filter.
        /// </summary>
        public static string APPLIED_FILTER_HEADER_TEXT {
            get {
                return ResourceManager.GetString("APPLIED_FILTER_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply date filter on expenses.
        /// </summary>
        public static string APPLY_FILTER_LABEL_TEXT {
            get {
                return ResourceManager.GetString("APPLY_FILTER_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string CHANGE_PASSWORD_SECTION_TEXT {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SECTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string CHANGE_PICTURE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CHANGE_PICTURE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core:.
        /// </summary>
        public static string COMP_Core_LABEL_TXT {
            get {
                return ResourceManager.GetString("COMP_Core_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsStorageOwner:.
        /// </summary>
        public static string COMP_IsStorageOwner_LABEL_TXT {
            get {
                return ResourceManager.GetString("COMP_IsStorageOwner_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer:.
        /// </summary>
        public static string COMP_Layer_LABEL_TXT {
            get {
                return ResourceManager.GetString("COMP_Layer_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module:.
        /// </summary>
        public static string COMP_Module_LABEL_TXT {
            get {
                return ResourceManager.GetString("COMP_Module_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string COMP_Name_LABEL_TXT {
            get {
                return ResourceManager.GetString("COMP_Name_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting component(s)....
        /// </summary>
        public static string DELETING_Components_WAIT_MSG {
            get {
                return ResourceManager.GetString("DELETING_Components_WAIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Some error occurred..
        /// </summary>
        public static string ERROR_OCCURED_MSG {
            get {
                return ResourceManager.GetString("ERROR_OCCURED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string EXPENSE_VIEW_HEADER {
            get {
                return ResourceManager.GetString("EXPENSE_VIEW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FILTER_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("FILTER_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by user.
        /// </summary>
        public static string FILTER_BY_USER_LABEL_TEXT {
            get {
                return ResourceManager.GetString("FILTER_BY_USER_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FILTER_HEADER_TEXT {
            get {
                return ResourceManager.GetString("FILTER_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter on amount: .
        /// </summary>
        public static string FILTER_ON_AMOUNT_LABEL_TXT {
            get {
                return ResourceManager.GetString("FILTER_ON_AMOUNT_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter on dates: .
        /// </summary>
        public static string FILTER_ON_DATE_LABEL_TXT {
            get {
                return ResourceManager.GetString("FILTER_ON_DATE_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter on user: .
        /// </summary>
        public static string FILTER_ON_USER_LABEL_TXT {
            get {
                return ResourceManager.GetString("FILTER_ON_USER_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FROM_LABEL_TEXT {
            get {
                return ResourceManager.GetString("FROM_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting transactions....
        /// </summary>
        public static string GETTING_TRANS_WAIT_MSG {
            get {
                return ResourceManager.GetString("GETTING_TRANS_WAIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting users....
        /// </summary>
        public static string GETTING_USERS_WAIT_MSG {
            get {
                return ResourceManager.GetString("GETTING_USERS_WAIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break up.
        /// </summary>
        public static string GRAPH_VIEW_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRAPH_VIEW_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string GRID_CompCore_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_CompCore_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsStorageOwner.
        /// </summary>
        public static string GRID_CompIsStorageOwner_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_CompIsStorageOwner_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string GRID_CompLayer_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_CompLayer_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string GRID_CompModule_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_CompModule_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GRID_CompName_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_CompName_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network name.
        /// </summary>
        public static string GRID_NodeName_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_NodeName_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string GRID_RoleName_HEADER_TEXT {
            get {
                return ResourceManager.GetString("GRID_RoleName_HEADER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About XPense.
        /// </summary>
        public static string HELP_WINDOW_HEADER {
            get {
                return ResourceManager.GetString("HELP_WINDOW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Configuration File.
        /// </summary>
        public static string HOME_VIEW_HEADER {
            get {
                return ResourceManager.GetString("HOME_VIEW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an image..
        /// </summary>
        public static string IMAGE_PICKER_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("IMAGE_PICKER_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to XPence.
        /// </summary>
        public static string LOGIN_SCREEN_HEADER {
            get {
                return ResourceManager.GetString("LOGIN_SCREEN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MANAGE_VIEW_HEADER {
            get {
                return ResourceManager.GetString("MANAGE_VIEW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MESSAGE_BOX_AFF_BUT_TEXT {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_AFF_BUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MESSAGE_BOX_NEG_BUT_TEXT {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_NEG_BUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NAME_LABEL_TXT {
            get {
                return ResourceManager.GetString("NAME_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NEW_PASSOWRD_LABEL_TEXT {
            get {
                return ResourceManager.GetString("NEW_PASSOWRD_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data exists..
        /// </summary>
        public static string NO_DATA_EXISTS_MSG {
            get {
                return ResourceManager.GetString("NO_DATA_EXISTS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network name:.
        /// </summary>
        public static string NODE_NetworkName_LABEL_TXT {
            get {
                return ResourceManager.GetString("NODE_NetworkName_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OFF_LABEL_TEXT {
            get {
                return ResourceManager.GetString("OFF_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OLD_PASSWORD_LABEL_TEXT {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ON_LABEL_TEXT {
            get {
                return ResourceManager.GetString("ON_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        public static string PASSWORD_LABEL_TEXT {
            get {
                return ResourceManager.GetString("PASSWORD_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re enter new password.
        /// </summary>
        public static string REENTER_NEW_PASSOWRD_LABEL_TEXT {
            get {
                return ResourceManager.GetString("REENTER_NEW_PASSOWRD_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ROLE_Name_LABEL_TXT {
            get {
                return ResourceManager.GetString("ROLE_Name_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Entity....
        /// </summary>
        public static string SAVING_Entity_WAIT_MSG {
            get {
                return ResourceManager.GetString("SAVING_Entity_WAIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving user....
        /// </summary>
        public static string SAVING_USER_WAIT_MSG {
            get {
                return ResourceManager.GetString("SAVING_USER_WAIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS_VIEW_HEADER {
            get {
                return ResourceManager.GetString("SETTINGS_VIEW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Theme.
        /// </summary>
        public static string THEME_SELECT_LABEL_TEXT {
            get {
                return ResourceManager.GetString("THEME_SELECT_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string TO_LABEL_TEXT {
            get {
                return ResourceManager.GetString("TO_LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expenditure:.
        /// </summary>
        public static string TOTAL_EXPENDITURE_LABEL_TXT {
            get {
                return ResourceManager.GetString("TOTAL_EXPENDITURE_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income:.
        /// </summary>
        public static string TOTAL_INCOME_LABEL_TXT {
            get {
                return ResourceManager.GetString("TOTAL_INCOME_LABEL_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new picture..
        /// </summary>
        public static string TP_CHANGE_PICTURE {
            get {
                return ResourceManager.GetString("TP_CHANGE_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete model(s)..
        /// </summary>
        public static string TP_DELETE_Models {
            get {
                return ResourceManager.GetString("TP_DELETE_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter models..
        /// </summary>
        public static string TP_FILTER_TRANS {
            get {
                return ResourceManager.GetString("TP_FILTER_TRANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to home..
        /// </summary>
        public static string TP_GOTO_HOME_BUTTON {
            get {
                return ResourceManager.GetString("TP_GOTO_HOME_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ABB.AC800PEC.DbConfigTool..
        /// </summary>
        public static string TP_INFO {
            get {
                return ResourceManager.GetString("TP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login..
        /// </summary>
        public static string TP_LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("TP_LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new model..
        /// </summary>
        public static string TP_NEW_Model {
            get {
                return ResourceManager.GetString("TP_NEW_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user..
        /// </summary>
        public static string TP_NEW_USER {
            get {
                return ResourceManager.GetString("TP_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the user list..
        /// </summary>
        public static string TP_REFRESH_USER {
            get {
                return ResourceManager.GetString("TP_REFRESH_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save model..
        /// </summary>
        public static string TP_SAVE_Model {
            get {
                return ResourceManager.GetString("TP_SAVE_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a user..
        /// </summary>
        public static string TP_SAVE_USER {
            get {
                return ResourceManager.GetString("TP_SAVE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings..
        /// </summary>
        public static string TP_SETTINGS {
            get {
                return ResourceManager.GetString("TP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the model..
        /// </summary>
        public static string TP_Update_Model {
            get {
                return ResourceManager.GetString("TP_Update_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string WAIT_SCREEN_HEADER {
            get {
                return ResourceManager.GetString("WAIT_SCREEN_HEADER", resourceCulture);
            }
        }
    }
}
